config/routes.rb
Rails.application.routes.draw do
  get 'characters/:id', as: 'character', to: 'characters#show'
  get 'characters', as: 'characters', to: 'characters#index' 
  get 'episodes_bcs/:id', as: 'episode_bcs', to: 'episodes_bcs#show'
  get 'episodes_bb/:id', as: 'episode_bb', to: 'episodes_bb#show'
  get 'seasons_bcs/:id', as: "season_bcs", to: 'seasons_bcs#show'
  get 'seasons_bb/:id', as: "season_bb",to: 'seasons_bb#show'
  root 'home#index'
  get 'error', as: 'errors', to: 'error#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApiError < StandardError; end

class ApplicationController < ActionController::Base
  rescue_from(ApiError, with: :error_master)
  rescue_from(URI::InvalidURIError, with: :error_master)

  def error_master
    redirect_to(errors_path)
  end

  def http_get(url)
    response = HTTParty.get(url)

    case response.code
      when 400...600
        flash[:alert] = "Error #{response.code}"
        raise ApiError.new 
    end

    return response
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    name_character = params[:id]
    @character_api = http_get("https://tarea-1-breaking-bad.herokuapp.com/api/characters?name=#{name_character}")[0]
    @quotes_api = http_get("https://tarea-1-breaking-bad.herokuapp.com/api/quote?author=#{name_character}")
  end

  def index  
    search_name = params[:search]
    @result_search = []
    offset = 0

    while @result_search.length % 10 == 0 || @result_search.empty?
      result = http_get("https://tarea-1-breaking-bad.herokuapp.com/api/characters?name=#{search_name}&limit=10&offset=#{offset}")
      @result_search.append(*result)
      offset += 10
      if result.empty?
        break
      end
    end
    
  end
end

app/controllers/episodes_bb_controller.rb
class EpisodesBbController < ApplicationController
  def show
    episode_id = params[:id]
    @episode =  http_get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes/#{episode_id}")[0]
  end
end

app/controllers/episodes_bcs_controller.rb
class EpisodesBcsController < ApplicationController
  def show
    episode_id = params[:id]
    @episode =  http_get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes/#{episode_id}")[0]
  end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
require 'httparty' 

class HomeController < ApplicationController
  def index
    episodes_bb =  http_get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Breaking+Bad')
    episodes_bcs =  http_get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Better+Call+Saul')

    @seasons_bb = episodes_bb.map {|var_bb| var_bb["season"]}.uniq
    @seasons_bcs = episodes_bcs.map {|var_bcs| var_bcs["season"]}.uniq  
  end
end

app/controllers/seasons_bb_controller.rb
class SeasonsBbController < ApplicationController
  def show
    @season = params[:id]
    episodes_api =  http_get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Breaking+Bad')

    @episodes = episodes_api.group_by {|var_bb| var_bb["season"]}[@season]
  end
end

app/controllers/seasons_bcs_controller.rb
class SeasonsBcsController < ApplicationController
  def show
    @season = params[:id]
    episodes_api =  http_get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Better+Call+Saul')

    @episodes = episodes_api.group_by {|var_bcs| var_bcs["season"]}[@season]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/episodes_bb_helper.rb
module EpisodesBbHelper
end

app/helpers/episodes_bcs_helper.rb
module EpisodesBcsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/seasons_bb_helper.rb
module SeasonsBbHelper
end

app/helpers/seasons_bcs_helper.rb
module SeasonsBcsHelper
end

app/views/characters/index.html.erb
<h3>Resultado Búsqueda</h3>

<% if @result_search.empty? %>
  <p>No hay resultados para esta búsqueda</p>

<% else %>
  <% @result_search.each do |result| %>
  <div><%= link_to result["name"], character_path(result["name"].gsub(".", ""))%></div>
  <%end%>

<%end%>

app/views/characters/show.html.erb
<h1><%=@character_api["name"]%></h1>

<div>
<%= image_tag(@character_api["img"], :height => '15%', :width => '15%') %>
<h4> Sobrenombre: <%= @character_api["nickname"]%></h4>
<h4> Actor/Actriz: <%= @character_api["portrayed"]%></h4>
<h4> Status: <%= @character_api["status"]%></h4>
<h4> Ocupación: </h4>
<% @character_api["occupation"].each do |occupation| %>
<p><%= occupation %></p>
<%end%>

<h4> Temporadas de Breaking Bad: </h4>
<% if @character_api["appearance"].empty? %>
<p>No aparece en esta serie</p>  
<% end %>
<% @character_api["appearance"].each do |appearance| %>
<span><%= link_to appearance, season_bb_path(appearance) %></span>
<%end%>

<h4> Temporadas de Call Saul: </h4>
<% if @character_api["better_call_saul_appearance"].empty? %>
<p>No aparece en esta serie</p>
<% end %>
<% @character_api["better_call_saul_appearance"].each do |better_call_saul_appearance| %>
<span><%= link_to better_call_saul_appearance, season_bcs_path(better_call_saul_appearance) %></span>
<%end%>
</div>


<h3>Citas</h3>
<% if @quotes_api.empty? %>
  <p>No hay citas</p>
<% end %>

<ul>
<% @quotes_api.each do |quote| %>
<li><%= quote["quote"] %></li>
<%end%>
</ul>

app/views/episodes_bb/show.html.erb
<h1><%= @episode["series"]%></h1>

<div>
<h3><%= @episode["title"] %></h3>
<h4> Temporada: <%= @episode["season"]%></h4>
<h4> Episodio: <%= @episode["episode"]%></h4>
<h4> Fecha estreno: <%= (@episode["air_date"])[0..9]%></h4>
<h4> Personajes: </h4>
<% @episode["characters"].each do |character| %>
<div><%= link_to character, character_path(character.gsub(".", "")) %></div>
<%end%>
</div>

app/views/episodes_bcs/show.html.erb
<h1><%= @episode["series"]%></h1>

<div>
<h3><%= @episode["title"] %></h3>
<h4> Temporada: <%= @episode["season"]%></h4>
<h4> Episodio: <%= @episode["episode"]%></h4>
<h4> Fecha estreno: <%= (@episode["air_date"])[0..9]%></h4>
<h4> Personajes: </h4>
<% @episode["characters"].each do |character| %>
<div><%= link_to character, character_path(character.gsub(".", "")) %></div>
<%end%>
</div>

app/views/home/index.html.erb
<h1>Tarea 1</h1>

<h3>Breaking Bad</h3>
<% @seasons_bb.each do |season_bb| %>
<div><%= link_to "Temporada #{season_bb}", season_bb_path(season_bb) %></div>
<%end%>

<h3>Better Call Saul</h3>
<% @seasons_bcs.each do |season_bcs| %>
<div><%= link_to "Temporada #{season_bcs}", season_bcs_path(season_bcs)%></div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="search">
      <%= form_tag(characters_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search]) %>
          <%= submit_tag("Buscar") %>
      <%end%>
    </div>

    <%= yield %>
  </body>
</html>

app/views/seasons_bb/show.html.erb
<h1>Breaking Bad</h1>

<h3>Temporada <%= @season %></h3>

<% if @episodes&.empty? %>
  <p>No hay episodios en esta temporada</p>
<% end %>

<ul class="list-group">
<% @episodes&.each do |episode| %>
<li class="list-group-item"><%= link_to episode["title"], episode_bb_path(episode["episode_id"]) %></li>
<%end%>
</ul>

app/views/seasons_bcs/show.html.erb
<h1>Better Call Saul</h1>

<h3>Temporada <%= @season %></h3>

<% if @episodes&.empty? %>
  <p>No hay episodios en esta temporada</p>
<% end %>

<% @episodes&.each do |episode| %>
<p><%=  link_to episode["title"], episode_bcs_path(episode["episode_id"]) %></p>
<%end%>